### ISSUE TITLE
Getting error when trying to run

### ISSUE THREAD

**Issue by Relms12345** [schenkd/nginx-ui#26]
I am trying to run the UI but I keep on getting "No such file or directory" error when trying to run it. Please help.

**Comment by LucaNerlich** [comment]
Please check the readme, you have most likely missed the volume mapping:

`docker run -d --restart=always --name nginxui -v /etc/nginx:/etc/nginx -p 8080:8080 schenkd/nginx-ui:latest`\

If not, can you please post your full error message? Thanks

**Comment by Relms12345** [comment]
got it working. thx

**Comment by LucaNerlich** [comment]
> got it working. thx

Could you share what exactly fixed your issue?

As of right now, this issue is not helpful to others.
