### ISSUE TITLE
Support openresty

### ISSUE THREAD

**Issue by hong-duc** [schenkd/nginx-ui#27]
Can you add support for openresty too ?
The only different between openresty and nginx is the name when run the command.

Reload:
nginx: `systemctl reload nginx`
openresty: `systemctl reload openresty`

Check config:
nginx: `nginx -t`
openresty: `openresty -t`

**Comment by schenkd** [comment]
Hello @hong-duc, thank you very much for your inquiry. Openresty has not been known to me until now. Thank you for bringing this to my attention. If what you say is true it should be no problem to make nginx-ui compatible for openresty. One approach which is not elaborate would be to create an alias on your server. For example alias nginx=openresty. That way you would have a quick solution for your problem. I think it is not useful if nginx-ui gets its own handling for openresty. I hope I could help you! I would be glad about feedback and would like to hear from you again and your experiences with nginx-ui!
