### ISSUE TITLE
[Suggestion] Implement nginxconfig.io

### ISSUE THREAD

**Issue by flying-sausages** [schenkd/nginx-ui#29]
Hey guys, just thought it would be cool to have a section that would integrate into this application which would expose the DigitalOcean's Nginx config "generator". I'm assuming that the "target audience" might really appreciate that.
https://github.com/digitalocean/nginxconfig.io
Curious what you guys think!

**Comment by schenkd** [comment]
Hey @flying-sausages , thanks for your input. This is a very good idea which we will also address as we have heard it many times as a suggestion. I like the idea of a generator for Nginx very much, as many of my colleagues also work with it very rarely and so don't have to study the documentation every time. Stay tuned and keep giving us feedback for improvements!

Best David

**Comment by flying-sausages** [comment]
Looking forward to it!
