### ISSUE TITLE
flask auth?

### ISSUE THREAD

**Issue by foozzi** [schenkd/nginx-ui#30]
Do I need to implement authorization based on flask? This will protect inexperienced users from unauthorized access by default.

**Comment by foozzi** [comment]
i'm found pretty look http auth for flask https://github.com/miguelgrinberg/Flask-HTTPAuth

**Comment by LucaNerlich** [comment]
You can use / built whatever auth you like. For Basic Auth, checkout the [readme](https://github.com/schenkd/nginx-ui#authentication)

**Comment by foozzi** [comment]
ok, but I meant to implement this by default for ease of use "out of the box"

**Comment by LucaNerlich** [comment]
This is already in the projects todo / inprogress board: https://github.com/schenkd/nginx-ui/projects/1#card-40880188
