### ISSUE TITLE
:latest crashes during startup

### ISSUE THREAD

**Issue by LucaNerlich** [schenkd/nginx-ui#6]
Im trying to setup nginx-ui, but executing `docker run -d --restart=always --name nginxui -p 7777:8080 schenkd/nginx-ui:latest -v /etc/nginx:/nginx` results in the container not starting correctly and constantly crashing.

`docker logs nginxui` results in the following message, without a real error info:

> *** Starting uWSGI 2.0.18 (64bit) on [Mon Jun 22 08:00:31 2020] ***
> compiled with version: 9.3.0 on 21 June 2020 09:42:26
> os: Linux-5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020
> nodename: eada146745a8
> machine: x86_64
> clock source: unix
> pcre jit disabled
> detected number of CPU cores: 1
> current working directory: /webapp
> detected binary path: /usr/local/bin/uwsgi
> uWSGI running as root, you can use --uid/--gid/--chroot options
> *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
> *** WARNING: you are running uWSGI without its master process manager ***
> your memory page size is 4096 bytes
> detected max file descriptor number: 1048576
> lock engine: pthread robust mutexes
> thunder lock: disabled (you can enable it with --thunder-lock)
> uWSGI running as root, you can use --uid/--gid/--chroot options
> *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
> uWSGI running as root, you can use --uid/--gid/--chroot options
> *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
> The -s/--socket option is missing and stdin is not a socket.

Any idea? Thanks :)

**Comment by mattheys** [comment]
pretty sure your volume mapping `-v /etc/nginx:/nginx` should come before the container name `schenkd/nginx-ui:latest`. 

If that doesn't fix it then it seems to be complaining about running as root so try passing in --user to map a non root user from your system in to the container but I don't think that is it.

**Comment by LucaNerlich** [comment]
The issue was with the volume mapping. Due to your example, I though nginxui expectes /etc/nginx to be mapped to ~/nginx inside your application/container, but instead it also looks for /etc/nginx.
Therefore executing `docker run -d --restart=always --name nginxui -v /etc/nginx:/etc/nginx -p 7777:8080 schenkd/nginx-ui:latest` works fine. Thanks for the response and the great work. :)

**Comment by mattheys** [comment]
Thanks, but it's not my work.
